name: WorkoutStatTracker
version: '0.5'
category: Web
author: CJ Meeks
maintainer: CJ Meeks
copyright: CJ Meeks
license: AllRightsReserved
github: cjmeeks/SeniorProject

dependencies:
- aeson
- base
- bytestring
- elm-export
- interpolate
- iproute
- network-uri
- servant
- servant-server
- string-conversions
- text
- time
- uuid
- wai

library:
  source-dirs: api
  exposed-modules:
  - Api.Types
  - Api.Helper
  - Api.Server
  - Api.Example.Types
  - Api.Example.Handler
  dependencies:
  - containers
  - data-default
  - cereal
  - exceptions
  - http-api-data
  - http-client
  - http-types
  - mtl
  - network
  - servant-client
  - transformers
  - pretty-simple
  - postgresql-simple
  - random

executables:
  app:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptonite
    - WorkoutStatTracker
    - wai-cors
    - warp

  code-generator:
    main: Main.hs
    source-dirs: code-generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WorkoutStatTracker
    - servant-elm
    - servant-foreign

tests:
  nfl-web-scraper-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - WorkoutStatTracker