development:
  adapter: postgresql
  database: senior_project
  encoding: utf8
  host: localhost
  port: 5432
  username: cjmeeks
  password: cjmeeksdb
production:
  adapter: postgresql
  database: senior_project
  encoding: utf8
  host: localhost
  port: 5432
  username: cjmeeks
  password: cjmeeksdb
